apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  selector:
    matchLabels:
      app: tasks
  replicas: 1
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: donyramadhan/kub-network-tasks:latest
          env:
            - name: TASKS_FOLDER
              value: "tasks"
            - name: AUTH_URL
              value: "auth-service.default"
