apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  selector:
    matchLabels:
      app: users
  replicas: 1
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: donyramadhan/kub-network-users:latest
          env:
            - name: AUTH_URL
              value: "auth-service.default"
